
Epoch 1/1000 - Train Loss: 2.5938, Train Accuracy: 0.2055
Epoch 1/1000 - Validation Loss: 2.3692, Validation Accuracy: 0.4221
Epoch 2/1000 - Train Loss: 2.4397, Train Accuracy: 0.3561
Epoch 2/1000 - Validation Loss: 2.3167, Validation Accuracy: 0.4524
Epoch 3/1000 - Train Loss: 2.3792, Train Accuracy: 0.4240
Epoch 3/1000 - Validation Loss: 2.3143, Validation Accuracy: 0.5065
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x00000251D7E58900>
Traceback (most recent call last):
  File "C:\Users\raul\.conda\envs\noestructurados\Lib\site-packages\torch\utils\data\dataloader.py", line 1479, in __del__
    self._shutdown_workers()
  File "C:\Users\raul\.conda\envs\noestructurados\Lib\site-packages\torch\utils\data\dataloader.py", line 1443, in _shutdown_workers
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "C:\Users\raul\.conda\envs\noestructurados\Lib\multiprocessing\process.py", line 149, in join
    res = self._popen.wait(timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\raul\.conda\envs\noestructurados\Lib\multiprocessing\popen_spawn_win32.py", line 110, in wait
    res = _winapi.WaitForSingleObject(int(self._handle), msecs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt:
[33m[W 2024-04-04 23:32:31,218][39m Trial 0 failed with parameters: {'n_layers': 5, 'lr': 7.434151977364627e-05, 'optimizer': 'Adam', 'unfreezed_layers': 9, 'dropout0': 0.12103850784192893, 'neuronas0': 179, 'dropout1': 0.1243750878960157, 'neuronas1': 100, 'dropout2': 0.350905594948295, 'neuronas2': 193, 'dropout3': 0.7964706729743066, 'neuronas3': 60, 'dropout4': 0.7254497038509901, 'neuronas4': 115} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "C:\Users\raul\.conda\envs\noestructurados\Lib\site-packages\optuna\study\_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "c:\Users\raul\Universidad Pontificia Comillas\Javier √Ålvarez Mart√≠nez - MachineLoooorning\DeepLearning\mainTraining.py", line 298, in objective
    accuracy = train_and_validate(model, device, train_loader, val_loader, epochs, optimizer,trial)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\raul\Universidad Pontificia Comillas\Javier √Ålvarez Mart√≠nez - MachineLoooorning\DeepLearning\mainTraining.py", line 177, in train_and_validate
    train_loss += loss.item()
                  ^^^^^^^^^^^
KeyboardInterrupt
[33m[W 2024-04-04 23:32:31,223][39m Trial 0 failed with value None.
Traceback (most recent call last):
  File "c:\Users\raul\Universidad Pontificia Comillas\Javier √Ålvarez Mart√≠nez - MachineLoooorning\DeepLearning\mainTraining.py", line 313, in <module>
    study.optimize(objective, n_trials=10000)  # Ajusta el n√∫mero de trials seg√∫n sea necesario
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\raul\.conda\envs\noestructurados\Lib\site-packages\optuna\study\study.py", line 451, in optimize
    _optimize(
  File "C:\Users\raul\.conda\envs\noestructurados\Lib\site-packages\optuna\study\_optimize.py", line 66, in _optimize
    _optimize_sequential(
  File "C:\Users\raul\.conda\envs\noestructurados\Lib\site-packages\optuna\study\_optimize.py", line 163, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\raul\.conda\envs\noestructurados\Lib\site-packages\optuna\study\_optimize.py", line 251, in _run_trial
    raise func_err
  File "C:\Users\raul\.conda\envs\noestructurados\Lib\site-packages\optuna\study\_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "c:\Users\raul\Universidad Pontificia Comillas\Javier √Ålvarez Mart√≠nez - MachineLoooorning\DeepLearning\mainTraining.py", line 298, in objective
    accuracy = train_and_validate(model, device, train_loader, val_loader, epochs, optimizer,trial)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\raul\Universidad Pontificia Comillas\Javier √Ålvarez Mart√≠nez - MachineLoooorning\DeepLearning\mainTraining.py", line 177, in train_and_validate
    train_loss += loss.item()
                  ^^^^^^^^^^^
KeyboardInterrupt